name: CMake

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get GCC-10
      run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10
      shell: bash

    - name: conan installation
      id: conan
      run:  |
            pip install conan
      shell: bash

    - name: gcovr installation
      id: gcovr
      run:  |
            pip install gcovr
      shell: bash

    - name: CMake configuration
      run:  |
            cmake -S ${{github.workspace}} \
            -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DTest=ON
      shell: bash
      env:
       CC:   gcc-10
       CXX:  g++-10

    - name: Cmake build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Cmake test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} && gcovr -r ../ . --cobertura-pretty > coverage.xml

    - uses: action-badges/create-orphan-branch@0.1.0
      with:
        branch-name: badges

    - name: Make Coverage Badge
      uses: action-badges/cobertura-coverage-xml-badges@0.2.1
      with:
        file-name: coverage.svg
        badge-branch: badges
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        coverage-file-name: ${{github.workspace}}/build/coverage.xml
